export { Header } from './Header/Header'
export { Hero } from './Hero/Hero'
export { ProfessionalSection } from './ProfessionalSection/ProfessionalSection'
export { ProfileDetail } from './ProfileDetail/ProfileDetail'
export { ContactSection } from './ContactSection/ContactSection'
export { SocialProof } from './SocialProof/SocialProof'
export { Footer } from './Footer/Footer'
